version: '3'
services:
  proxy:
    image: nginx:1.13.9-alpine
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d
    command: [nginx, '-g', 'daemon off;']
    extra_hosts:
      - "nginxhost:${NGINX_HOST}"
